### ISSUE TITLE
I cannot find it in Integrations once I have added it via HACS

### ISSUE THREAD

**Issue by daven1985** [troykelly/homeassistant-au-nsw-covid#2]
Added to HACS... all fine.

But can't add via normal integrations. It never turns up.

**Comment by troykelly** [comment]
Okay, I've clearly done something bad. Having a look now.

**Comment by daven1985** [comment]
All good. Just happy to help in anyway I can.

**Comment by troykelly** [comment]
From what I can see it's the error below - which is caused because the library is [not listed in the wheels](https://github.com/home-assistant/wheels-custom-integrations/pull/462).
Will be able to test properly when that PR is completed.
```text
2021-08-01 03:22:11 ERROR (MainThread) [homeassistant.setup] Setup failed for nswcovid>=0.0.6: Integration not found.
2021-08-01 03:22:11 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of nswcovid. Setup failed for dependencies: nswcovid>=0.0.6
2021-08-01 03:22:11 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/python/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/python/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/python/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/local/python/lib/python3.9/site-packages/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/local/python/lib/python3.9/site-packages/homeassistant/components/http/forwarded.py", line 77, in forwarded_middleware
    return await handler(request)
  File "/usr/local/python/lib/python3.9/site-packages/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/local/python/lib/python3.9/site-packages/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/local/python/lib/python3.9/site-packages/homeassistant/components/http/auth.py", line 144, in auth_middleware
    return await handler(request)
  File "/usr/local/python/lib/python3.9/site-packages/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/usr/local/python/lib/python3.9/site-packages/homeassistant/components/config/config_entries.py", line 128, in post
    return await super().post(request)
  File "/usr/local/python/lib/python3.9/site-packages/homeassistant/components/http/data_validator.py", line 63, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/local/python/lib/python3.9/site-packages/homeassistant/helpers/data_entry_flow.py", line 72, in post
    result = await self._flow_mgr.async_init(
  File "/usr/local/python/lib/python3.9/site-packages/homeassistant/data_entry_flow.py", line 153, in async_init
    flow, result = await task
  File "/usr/local/python/lib/python3.9/site-packages/homeassistant/data_entry_flow.py", line 171, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/usr/local/python/lib/python3.9/site-packages/homeassistant/config_entries.py", line 693, in async_create_flow
    await async_process_deps_reqs(self.hass, self._hass_config, integration)
  File "/usr/local/python/lib/python3.9/site-packages/homeassistant/setup.py", line 371, in async_process_deps_reqs
    raise HomeAssistantError("Could not set up all dependencies.")
homeassistant.exceptions.HomeAssistantError: Could not set up all dependencies.
```

**Comment by daven1985** [comment]
Version 0.0.6 appears to have fixed all issues. I can add them to integrations and it has loaded.

Looks good! Never expected this much data!

Can you get infectus in the community last 24 hours?

**Comment by troykelly** [comment]
@daven1985 I'd like that too (infectious in the community) but it's not a number they publish.
It's just given out at the press conference every morning.
Their reasoning a few press conferences was that it changes throughout the day as they contact trace - so it's too fluid a number.

If you want the total local cases - I've created an [example template sensor](https://github.com/troykelly/homeassistant-au-nsw-covid/blob/main/README.md#local-cases-all-of-nsw)

**Comment by troykelly** [comment]
Closed as resolved.
Reopen if the issue comes back with the latest version - I've tested it a fair bit and it looks okay
