### ISSUE TITLE
ValueError on Startup

### ISSUE THREAD

**Issue by bacco007** [troykelly/homeassistant-au-nsw-covid#38]
Something in the dataset must have changed, looks like its trying to convert unicode(?) to an integer

```
2021-08-11 11:27:53 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry NSW Covid for nswcovid
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/nswcovid/__init__.py", line 36, in async_setup_entry
    if not await hass.data[DOMAIN][entry.entry_id].refresh():
  File "/usr/local/lib/python3.9/site-packages/nswcovid/API/main.py", line 26, in refresh
    await self.__statistics_handler.build()
  File "/usr/local/lib/python3.9/site-packages/nswcovid/protocol/statistics.py", line 87, in build
    await task
  File "/usr/local/lib/python3.9/site-packages/nswcovid/protocol/statistics.py", line 345, in refresh
    await self.__handler.details(self.__id)
  File "/usr/local/lib/python3.9/site-packages/nswcovid/protocol/statistics.py", line 213, in details
    value = int(value.replace(",", ""))
ValueError: invalid literal for int() with base 10: '\u200b670314'
```

**Comment by troykelly** [comment]
Thank you - this should be resolved by #36 - which has been released as [Version 0.1.9](https://github.com/troykelly/homeassistant-au-nsw-covid/releases/tag/v0.0.19)

Let me know if that isn't working for you.
