### ISSUE TITLE
Fix changes to measurement requirements

### ISSUE THREAD

**Issue by troykelly** [troykelly/homeassistant-au-nsw-covid#46]
Per https://github.com/troykelly/homeassistant-au-nsw-covid/issues/44#issuecomment-908898200
Changes need to be made to align with https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics

**Comment by troykelly** [comment]
@DavidFW1960 sorry, this might take a minute to get fixed.
I think the removal of `last_reset` by the devs is an error - I've posed my question here - https://community.home-assistant.io/t/confusion-with-removal-of-last-reset-on-long-term-statistics/334408

Once I get an understanding of what to do with `last_reset` I will try and re-implement long-term-statistics.

**Comment by DavidFW1960** [comment]
no rush. It's annoying error but not fatal.

**Comment by troykelly** [comment]
It seems the fix has broken it good and proper.
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 498, in _async_add_entity
    capabilities=entity.capability_attributes,
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 135, in capability_attributes
    if state_class := self.state_class:
  File "/config/custom_components/nswcovid/sensor.py", line 324, in state_class
    return sensor.STATE_CLASS_TOTAL_INCREASING
AttributeError: module 'homeassistant.components.sensor' has no attribute 'STATE_CLASS_TOTAL_INCREASING'
```
